### PR TITLE
Add left nav UI prototype

### PR DESCRIPTION
**Pull request by anmol-algo**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@anmol-algo Can you share with me how I'm supposed to preview this prototype?

**Comment by mojavelinux** [comment]
I think the prototype is in the nav-ui folder. However, when I view it, the icons in the blue navbar are huge and cover most of the screen. Can you adjust the size so that the navbar is contained?

**Comment by anmol-algo** [comment]
Hi @mojavelinux Fixed the icon size Please review.

**Comment by mojavelinux** [comment]
Yep, that works now. Thanks!

**Pull request closed without merging**
