### PR TITLE
View source url style

### PR DESCRIPTION
**Pull request by rakeshAlgo**
Hi @amarantha-k ,
I  implemented a view-source icon on code blocks.

### CODE REVIEW

**Review by amarantha-k — APPROVED** [review]

**Comment by amarantha-k** [comment]
@mojavelinux The deploy preview looks good to me. Could you review and let Rakesh know if any changes are required? Thx

**Review by mojavelinux — APPROVED** [review]
Yep, that works.

@amarantha-k One question I had for you was about the terminology. Before we commit to it on both ends, I want to make sure we have it right. Does data-source-url make sense to you? Or should it be data-view-source-url or something else?

**Comment by amarantha-k** [comment]
Yes, data-source-url makes sense.

**Comment by mojavelinux** [comment]
I noticed that this isn't using the Font Awesome icon from Font Awesome. Though since it's added dynamically, we'd need a way to preregister icons that aren't found in the HTML. That is something we could do.

**Pull request merged**
