### PR TITLE
Fix the alignment issues for image icon and definition list

### PR DESCRIPTION
**Pull request by rakeshAlgo**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@rakeshAlgo Could you resolve the merge conflicts please?

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k ,
I resolved the conflict, Please check.

**Review by amarantha-k — APPROVED** [review]

**Comment by amarantha-k** [comment]
@mojavelinux The deploy preview fails with an error in netlify.toml. Could you take a look please?

**Comment by mojavelinux** [comment]
@amarantha-k The failure is due to a CSS syntax error. The fact that it throws an exception instead of reporting the error is something I need to address (the linter API changed and I need to backport the fix from the default UI).

**Comment by mojavelinux** [comment]
If you rebase against master, the crash will be fixed. You will then be able to see the source of the CSS error.

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k ,
I rebase this branch against master.  And after that, I fixed CSS Error and resolved the conflict. Please look into this.

**Pull request merged**
