### PR TITLE
change fluid layout into box layout container

### PR DESCRIPTION
**Pull request by rakeshAlgo**
Hi @amarantha-k ,
I have a container layout with a 1440px max-width. Please look into the PR .

### CODE REVIEW

**Comment by amarantha-k** [comment]
As discussed in the call, please update so left side continues to have the light gray background. Thanks.

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k ,
I have implemented two layouts for continues to gray background. Please suggest which one is good.

**Layout - 1** 
image

**Layout - 2**
image

**Comment by amarantha-k** [comment]
Let's go with layout 1 please

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k ,
I have updated layout 1. Please look into the PR.

**Review by amarantha-k — APPROVED** [review]
looks good. thx

**Pull request merged**
