### PR TITLE
integrate Font Awesome Pro 5 into UI preview

### PR DESCRIPTION
**Pull request by mojavelinux**
This is a first draft of the Font Awesome Pro 5 integration for the UI preview. In order for this to work fully, you must first add the following file to the root folder of the UI project:

.npmrc

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=INSERT_TOKEN_HERE
```

Replace INSERT_TOKEN_HERE with the Font Awesome Pro API token. Then run `npm i`

```
npm i
```

The icons will be loaded as needed.

If you don't add an .npmrc file, the UI preview will still work, but some icons will be missing.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I want to update this to fallback to the free icons so that only the pro icons will be missing if the API token is not specified.

I also am thinking about writing the defs to a shared file instead of directly to the pages. So I may still do some tweaking. In the meantime, it would be great if you could have Rakesh test it.

**Comment by amarantha-k** [comment]
@rakeshAlgo Can you test this PR please?

**Review by amarantha-k — APPROVED** [review]
Adding my approval if you want to merge this today. Have tagged Rakesh on the PR to test it.

**Comment by rakeshAlgo** [comment]
Hi @mojavelinux ,
Free version icon UI preview working fine, but pro icons are missings because of authToken.
So please add .npmrc file with Font Awesome Pro API token.

**Comment by mojavelinux** [comment]
@rakeshAlgo If I were to add the auth token to the repository, that would effectively make Couchbase's Font Awesome Pro license key public. So no, I cannot do that.

You must add this file to your local worktree (and make sure not to commit it). @amarantha-k will need to provide you with the auth token.

**Comment by mojavelinux** [comment]
@amarantha-k I'm still making some adjustments that's going to allow this to work in the real site build. Instead of adding the icons defs directly into the HTML, I'm going to write them to a shared JavaScript file. That way, we don't have to manipulate the HTML of all the pages.

**Comment by amarantha-k** [comment]
@mojavelinux We discussed this on the call tonight and think it may be better to merge the code when your updates are ready and Rakesh can then test the sandbox site.

**Comment by amarantha-k** [comment]
@mojavelinux Can I merge this PR?

**Comment by graphitefriction** [comment]
@amarantha-k Not quite yet - we're confirming that the corresponding PR here: https://github.com/couchbase/docs-site/pull/215 is working as expected and there seems to be an inconsistency between Font Awesome's docs and reality 🙄

**Comment by mojavelinux** [comment]
@amarantha-k This is now ready.

To summarize, the UI preview will use the pro icons if installed, falling back to the free icons if they are not. Installing the pro icons locally or in CI requires creating an .npmrc file that contains the auth token for the pro packages. If that is not present, those packages will simply be skipped.

**Pull request merged**
