### PR TITLE
Ui bug fixes for docs-Sandbox-Site-Validation

### PR DESCRIPTION
**Pull request by rakeshAlgo**
Hi @amarantha-k ,
I have fixed today sync up UI issues from docs.
Please look into the PR.

### CODE REVIEW

**Comment by amarantha-k** [comment]
@rakeshAlgo As seen in the design, Open Sans is used in the left-nav as well. Please update.
Rest of the changes look good.

**Comment by rakeshAlgo** [comment]
No @amarantha-k ,
In new style guide source sans pro is used for left nav. 
Please see the screenshot.

image

**Comment by amarantha-k** [comment]
Sorry - my bad. I was looking at component-LP-1.

**Review by amarantha-k — APPROVED** [review]
lgtm

**Pull request merged**
