### PR TITLE
implement the Run Code interaction for designated source code blocks

### PR DESCRIPTION
**Pull request by anmol-algo**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@anmol-algo Please use class="fas fa-terminal" for the icon.

**Comment by amarantha-k** [comment]
@mojavelinux The UI has been updated to include the terminal(shell) view. Would you be able to take this and integrate with the backend changes?

**Comment by amarantha-k** [comment]
@mojavelinux The Playground now includes custom code to handle requests coming from the Docs site. In order to invoke this, we need to include a “from” parameter in the form with the value set to “docs”. Could you please add this to our request?

**Comment by mojavelinux** [comment]
@amarantha-k I have added the from parameter to the request.

**Pull request merged**
