### PR TITLE
add search filter and pagination to search results

### PR DESCRIPTION
**Pull request by mojavelinux**
- add filter pane to right of search results for filtering by component and version
- add pagination controls to search results
- don't show search box if Algolia environment variables are not set
- add restore search functionality to search box

### CODE REVIEW

**Comment by mojavelinux** [comment]
There's still some work I need to do on this. Stay tuned.

**Comment by amarantha-k** [comment]
@mojavelinux 
Reviewed the deploy preview and need two minor updates: 
- For consistency, can we use the Font Awesome icon fa-chevron-down for the version drop-down in the filter? 
- In the version drop-down, rename `*` to "All (*)"

**Review by amarantha-k — COMMENTED** [review]
Requested UI changes

**Comment by mojavelinux** [comment]
> In the version drop-down, rename * to "All (*)"

Good suggestion. I can make that update.

> For consistency, can we use the Font Awesome icon fa-chevron-down for the version drop-down in the filter?

I tried to apply some styling to the menu, but it's inheriting global styles that makes it really complex for someone just walking into it. I would rather have the UI designer come behind and handle that.

**Comment by mojavelinux** [comment]
Another change request from the email thread:

> Could we update the pagination in the UI to use the following order? [< Prev] [Page x of y] [Next >]

**Comment by amarantha-k** [comment]
> > In the version drop-down, rename * to "All (*)"
> 
> Good suggestion. I can make that update.
> 
> > For consistency, can we use the Font Awesome icon fa-chevron-down for the version drop-down in the filter?
> 
> I tried to apply some styling to the menu, but it's inheriting global styles that makes it really complex for someone just walking into it. I would rather have the UI designer come behind and handle that.

Sounds good. I'll work with the UI designer to update that.

**Review by amarantha-k — APPROVED** [review]
Approving as the functionality looks good. 
The next step is to  work with the UI designer to update the styling for the version drop-down in the filter.

**Comment by mojavelinux** [comment]
That sounds good!

**Pull request merged**
