### PR TITLE
integrate Asciidoctor Tabs

### PR DESCRIPTION
**Pull request by mojavelinux**
This PR provides a reference for how to integrate Asciidoctor Tabs. It depends on #162.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Some styling work is still needed.

**Comment by osfameron** [comment]
Amazing, thanks! I'll look at integrating these 2 PRs this week

**Comment by osfameron** [comment]
OK, I see what you mean - the element names and labelling have changed, bringing in line best-practices like ARIA roles and other bits.

A quick hack-hack-hack attempt with the existing doc.css didn't get me anywhere, so I'll do a full comparison of the HTML changes and figure it out.

**Comment by osfameron** [comment]
Merged via https://github.com/couchbase/docs-ui/pull/165

**Pull request closed without merging**
