### PR TITLE
add support for navigation entries that contain a fragment identifier

### PR DESCRIPTION
**Pull request by mojavelinux**
Backported fix from Antora Navigator. See https://gitlab.com/opendevise/oss/antora-navigator-extension/-/merge_requests/4

### CODE REVIEW

**Comment by RichardSmedley** [comment]
Thanks @mojavelinux 
Much appreciated!

@osfameron is out-of-office today, so I'll leave the merge for him tomorrow - but LGTM  :+1:

**Review by osfameron — APPROVED** [review]
Thanks Dan! This does work with one minor niggle.

e.g. 
1. OK: Choose SDK 4.1, click on "Project Docs -> Release Notes"
The nav menu syncs to the fragment. Great!

2. STILL OK: from here, now choose SDK 4.3
It looks like choosing a version from the dropdown **loses the fragment**, which in this case happens to be correct, and we arrive at the fragmentless URL, which matches nav, and syncs.

3. NOT OK: Now choose SDK 4.1 again.
This goes to the URL without the fragment.
As the one in the Nav has a fragment, they now don't match, and the nav menu does NOT sync.

So, case 1 fixes the problem we reported, thanks!

Case 3 isn't great though. It'll be easy to follow the workflow of "Arrive on Current version, choose Release Notes, now switch to older version".

Do you need to support cases where the Nav menu links to the same URL multiple times at different fragments?
(If not, the simple fix of matching the URL only could fix this.
Potentially if *you* need to support the case, but *we* don't, we could add that simplified handling locally?)


Anyway, this is a great improvement, I'll merge, and invoke @RichardSmedley to advise on how big a problem the remaining issue is for him.

**Comment by mojavelinux** [comment]
The navigation system makes an assumption that switching versions should not preserve the fragment. However, that could be added. It's not possible to drop the fragment, then restore it when switching back to a version since once it's gone, it's gone. It either has to be preserved or not preserved. It sounds like preserving would work best for you. I can come up with a PR to show how that is done.

**Comment by mojavelinux** [comment]
Preserving the hash (aka URL fragment) on version change is a universal change. See https://github.com/couchbase/docs-ui/pull/184

**Pull request merged**
