### PR TITLE
update UI to account for versionless component with empty version

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by osfameron** [comment]
Thanks Dan - this doesn't quite work, as in our build, nav.hbs never descends into the nav-menu.hbs template, because `{{#if (eq (nav-mode) 'template')}}` doesn't hold (it's 'client').

I've modified the logic for choosing `versioned` instead, which seems to fix both our issues (e.g. shows the dropdown and hides the duplicate nav) see https://github.com/couchbase/docs-ui/commit/c0229406811d8129cc0a34ecb4e3d35bcd9396ac

**Comment by mojavelinux** [comment]
> this doesn't quite work, as in our build, nav.hbs never descends into the nav-menu.hbs template

The UI is designed to support both modes for when one mode is needed over another...and the UI preview allows you to switch. Unless the logic for template is removed, both modes should be kept updated.

**Comment by osfameron** [comment]
I couldn't see how to switch `nav-mode` between `template` and `client`.
(And quick search doesn't find it documented in e.g. https://docs.antora.org/antora-ui-default/ )
Where should I look for more details on this?

**Comment by osfameron** [comment]
Ah ok, `ui-model.yml` for the preview-src has the option of template or client, and is set to `template`.
This is presumably what guides the `npx gulp preview` build locally?

However as we're testing a build e.g. `npx gulp bundle` and antora build on staging, it defaults to `client`.
I don't see how to switch that in e.g. docs-site?

**Comment by mojavelinux** [comment]
> This is presumably what guides the npx gulp preview build locally?

That's correct.

> However as we're testing a build e.g. npx gulp bundle and antora build on staging, it defaults to client.

That is also correct. The decision is made by the following helper, and is based on the site configuration: https://github.com/couchbase/docs-ui/blob/master/src/helpers/nav-mode.js

**Comment by mojavelinux** [comment]
You definitely want to be using "client" for the big production sites because it is more efficient. However, the UI was designed so that it doesn't have to be used by all sites since it requires extra configuration. And, at the time, there was a migration taking place which required both.

**Comment by osfameron** [comment]
OK, that makes sense, thanks!

Presumably it's reasonable to set the default of the preview build to `client` to reflect our usage?
(This would have confused me if I'd used the preview in this case...)

**Comment by mojavelinux** [comment]
Yes, it should work with either...and once you confirm it does, you can set it to client.

**Pull request merged**
