### PR TITLE
version dropdown issues fixes

### PR DESCRIPTION
**Pull request by rakeshAlgo**
Hi @amarantha-k ,
Sorry for the delay, but version dropdown issues were a little tricky that's why it has taken more time.
Now I change mouse hover behavior, the earlier dropdown is open when we hover on version number but now it is open when we hover on version title as well.
Please look into the PR is good to go?

### CODE REVIEW

**Comment by amarantha-k** [comment]
@rakeshAlgo Do you have a local build with component "Autonomous Operator 2.0"? It'll be good if you can add a screenshot.

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k ,
Please find the attachment below.

image

**Comment by amarantha-k** [comment]
@rakeshAlgo Thanks! Can we have the version number wrap with the last word of the component name? So in this case, it would be:
“Autonomous 
  Operator 2.0 >”

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k ,
Sure I"ll do this. Please see in the screenshot It will look like this - 

image

**Comment by amarantha-k** [comment]
@rakeshAlgo this looks better. We need to update the font, font size, and spacing as per design.

**Comment by rakeshAlgo** [comment]
Sure @amarantha-k , I"ll do this.

**Pull request merged**
