### PR TITLE
load required icons

### PR DESCRIPTION
**Pull request by mojavelinux**
- allow icons to be specified explicitly as required in src/js/vendor/fontawesome-icon-defs.js
- use copy icon from Font Awesome in source block toolbar
- use GitHub icon from Font Awesome in source block toolbar
- fix styles for source block toolbar
- add Font Awesome placeholder for section title anchors
- use link icon from Font Awesome for section title anchors
- fix styles for section title anchors

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux could you rebase this PR please?

**Review by amarantha-k — COMMENTED** [review]
Looks good to merge once the conflict is resolved.

**Comment by mojavelinux** [comment]
This still needs a little work, and it also relates to the heading link
anchors. Expect updates shortly.

**Comment by mojavelinux** [comment]
@amarantha-k This is now ready. It also resolves the broken anchor/link icons on section titles.

**Review by amarantha-k — APPROVED** [review]
Functionality looks good. 
Noting that the H2 anchor link icons are not subtle, but it may be my preference. Once we see it on the site, we may want to consider tweaking it a bit.

**Comment by mojavelinux** [comment]
@amarantha-k Now that we're loading the icons referenced by the templates or JavaScript, the next step would be to use Font Awesome for the admonition icons. That requires updating the 11-page-customize.js to tweak the CSS class on the icon element so that the Font Awesome icon script detects and replaces it.

In other words, replacing `<i class="fa icon-tip" title="Tip"></i>` with `<i class="far fa-star" title="Tip"></i>`. (Current, the script is removing the fa class in order to hide it).

**Pull request merged**
