### PR TITLE
Sandbox UI bug fixes

### PR DESCRIPTION
**Pull request by rakeshAlgo**
Hi @amarantha-k ,
In this PR I have covered the following issues - 

**1) From Docs-Sandbox-Site-Validation doc sheet -** 
    a) 25
    b) 28 
    c) 29
  **Note -** For 28 points I think, all icon is set correctly on staging site https://docs-staging.couchbase.com/tutorials/index.html .
   and if you want to update the filter dropdown, so you can edit tutorials-filter.hbs page.

**2) Today SyncUp Feedback**
        a) Remove border left on hover in the right sidebar.
       b) Fix indentation on all .hbs file.

### CODE REVIEW

**Review by amarantha-k — APPROVED** [review]

**Comment by amarantha-k** [comment]
@rakeshAlgo Could you please resolve the conflicts?

**Comment by rakeshAlgo** [comment]
Ok, Let me check.

**Comment by rakeshAlgo** [comment]
Hi @amarantha-k , 
Have you deleted the ui-bug-fixes branch?

**Comment by amarantha-k** [comment]
It's restored now

**Comment by rakeshAlgo** [comment]
Thanks for restoring the branch.

**Pull request merged**
