### PR TITLE
Adding next/previous pagination to the site. If you want add forward/…

### PR DESCRIPTION
**Pull request by RayOffiah**
Adding next/previous pagination to the docs site.

### CODE REVIEW

**Review by simon-dew — CHANGES_REQUESTED** [review]
@RayOffiah — I've tried building this locally and I can't get the Next and Previous links to appear. Please can you add the `:page-pagination:` doc attribute to [preview-src/index.adoc](https://github.com/couchbase/docs-ui/blob/master/preview-src/index.adoc) so that we can see the Next and Previous links in action.

**Comment by RayOffiah** [comment]
Will do.

**Comment by RayOffiah** [comment]
@simon-dew 

Okay, the problem is that the preview code needed a bit of tweaking. The pagination code relies on the data in the nav.adoc file, which the the gulp preview function doesn't use. Fortunately, there's a way to fake a menu in the preview config file, so it should show up now.

**Review by simon-dew — APPROVED** [review]
LGTM :+1:

**Review by simon-dew — APPROVED** [review]

**Comment by simon-dew** [comment]
Huh, I don't have write access. I'll request a review from the whole docs team.

**Review by RichardSmedley — APPROVED** [review]
:+1:

**Review by maria-robobug — APPROVED** [review]

**Pull request merged**
