### PR TITLE
Doc 10193 sort out the spacing between admonition blocks and surrounding text

### PR DESCRIPTION
**Pull request by RayOffiah**
Fixing admonition layouts, one problem at a time …

https://issues.couchbase.com/browse/DOC-10193

### CODE REVIEW

**Comment by osfameron** [comment]
Isn't `!important` a red flag btw?

... Now that I say that, I remember the last CSS I added from @simon-dew had it too, and I didn't even think about it... 
so OK for expedience, if this fixes a current problem!

But is it worth us having a look at how to rework the CSS without sprinkling that around, as it will likely bite us later?

**Comment by RayOffiah** [comment]
> Isn't `!important` a red flag btw?
> 
> ... Now that I say that, I remember the last CSS I added from @simon-dew had it too, and I didn't even think about it... so OK for expedience, if this fixes a current problem!
> 
> But is it worth us having a look at how to rework the CSS without sprinkling that around, as it will likely bite us later?

The way the CSS is organised, the admonitions take on a different look depending on what list they are inside and possibly what depth because their settings are overridden by the list/callout lists/whatever else.  What they should do is have the same look and spacing no matter where they are.

So rather than adjusting all the layout elements to add an exception for the admonitions rule (and I'm certainly going to need a couple of iterations to find them all), it's a lot easier (and IMO, more maintainable) to tell the CSS that we want the same look and feel for the admonitions, no matter where they are in the page hierarchy.

There are different schools of thought on using `!important`. Most agree that it should be used sparingly, but I lean more towards, _Yup, use it, but make sure you understand why you're using it._

**Review by osfameron — APPROVED** [review]
OK, the revised version is just adding specificity to avoid !important?

Sure either version are fine for now, thanks for tackling these CSS niggles!
We could perhaps usefully discuss within team if we need to skill up on this, or borrow some UI resource to tidy things up later?

**Comment by simon-dew** [comment]
As a matter of style and tone I think we ought to use admonition blocks sparingly. Personally I would avoid using one in the middle of a callout list. That said, if you _need_ to use one in the middle of a callout list, the spacing should be correct, so LGTM 👍

**Pull request merged**
