### PR TITLE
Update tutorial filter options

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@rakeshAlgo In the deploy preview, i'm unable to select the checkboxes for role = "Mobile Developer" and language = "Node.js". Could you take a look please?

**Comment by rakeshAlgo** [comment]
Okay @amarantha-k , Let me check.

**Comment by rakeshAlgo** [comment]
Amarantha, Please make the same name **input id** and **label for .**

```
<li>
                            <input type="checkbox" id="mobile" class="check-mark" name="role" value="mobile">
                            <label for="mobile">Mobile Developer</label>
                        </li>
```
image

on deploy preview, this is different for the mobile developer and node js. 
So make those things with the same name.

**Comment by amarantha-k** [comment]
@rakeshAlgo Thanks for catching that! Please take a look now

**Comment by amarantha-k** [comment]
Verified in deploy preview that it works.

**Pull request merged**
